# Page settings

baseURL = ""
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = ""






[params]
    author = "Joshua Ward"
    description = "My Software Engineering Journey!"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Joshua Ward"
        tagline = "Technical Lead Software Engineer"
        avatar = "professional-avatar.jpeg"







    [params.contact]
        enable = true
        location = "Morgantown, WV"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "304-667-7498"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "j2udevelopment@gmail.com"
    #    [[params.contact.list]]
    #    icon = "fas fa-globe"
    #    url = "#"
    #    text = "www.yourwebsite.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Java"
        [[params.skills.list.items]]
        details = "Kubernetes, Helm, Skaffold, Docker"
        [[params.skills.list.items]]
        details = "Terraform, AWS"        
        [[params.skills.list.items]]
        details = "Apache Kafka, Apache NiFi, MongoDB, Prometheus/Grafana, Istio, Jenkins"
        [[params.skills.list.items]]
        details = "Git, Atlassian, Hugo"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Leadership"
        [[params.skills.list.items]]
        details = "Strong problem solver"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Electrical Engineering with a focus on Computer Systems and Software Engineering"
        university = "West Virginia University"
        dates = "2015 - 2017"
        [[params.education.list]]
        degree = "BSc Computer Engineering"
        university = "West Virginia University"
        dates = "2010 - 2015"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/j2udevelopment"
        title = "Joshua Ward"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/joshua-ward-78997612a"
        title = "Joshua Ward"
        # [[params.social.list]]
        # icon = "fab fa-twitter-square"
        # url = "//twitter.com/username"
        # title = "@username"





